name: Checkstyle

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build e execução do Checkstyle
        run: |
          mvn clean install
      - name: Verificar Checkstyle
        run: |
          mvn checkstyle:check -Dcheckstyle.failOnViolation=true