name: Checkstyle

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build e execução do Checkstyle
        run: |
          mvn clean install

      - name: Verificar Checkstyle
        run: |
          mvn checkstyle:check -Dcheckstyle.failOnViolation=true

      - name: Definir status de verificação
        if: failure()
        run: |
          echo "::set-output name=status::failure"
        else:
          echo "::set-output name=status::success"

      - name: Atualizar status de verificação no GitHub
        run: |
          token="${{ secrets.GITHUB_TOKEN }}"
          repo="${{ github.repository }}"
          pr="${{ github.event.pull_request.number }}"
          status="${{ steps.build.outputs.status }}"
          gh api "repos/$repo/statuses/$pr" -f "state=$status" -f "context=Checkstyle"
